# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: MarioZZJ's blog
subtitle: 'MarioZZJ个人博客'
description: ''
keywords:
author: MarioZZJ
language: zh-CN
timezone: ''
email: mariozzj@outlook.com

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://blog.mariozzj.cn/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

# 导航菜单
## https://butterfly.js.org/posts/4aa8abbe/#%E5%B0%8E%E8%88%AA%E8%8F%9C%E5%96%AE
menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  清單||fa fa-heartbeat:
    音樂: /music/ || fas fa-music
    照片: /Gallery/ || fas fa-images
    電影: /movies/ || fas fa-video
  友链: /link/ || fas fa-link
  关于: /about/ || fas fa-heart

# 代码
## https://butterfly.js.org/posts/4aa8abbe/#%E4%BB%A3%E7%A2%BC
highlight_theme: mac
highlight_copy: true
highlight_shrink: false
code_word_wrap: true
highlight_height_limit: 200px

# 社交图标
## https://butterfly.js.org/posts/4aa8abbe/#%E7%A4%BE%E4%BA%A4%E5%9C%96%E6%A8%99
social:
  fab fa-github: https://github.com/MarioZZJ || Github
  fas fa-envelope: mailto:mariozzj@outlook.com || Email
  fab fa-zhihu: https://www.zhihu.com/people/MarioZZJ || 知乎
  fab fa-linkedin: https://www.linkedin.com/in/mariozzj/ || 领英
  fab fa-qq: https://qm.qq.com/cgi-bin/qm/qr?k=h84pms0BX6LZg6soeFF-GU0v8Cnqc3Op&noverify=0 || QQ
  fas fa-tv-retro: https://space.bilibili.com/28623387 || Bilibili

# 主页文章节选
## https://butterfly.js.org/posts/4aa8abbe/#%E4%B8%BB%E9%A0%81%E6%96%87%E7%AB%A0%E7%AF%80%E9%81%B8-%E8%87%AA%E5%8B%95%E7%AF%80%E9%81%B8%E5%92%8C%E6%96%87%E7%AB%A0%E9%A0%81description
index_post_content:
  method: 2
  length: 100

# 文章封面
## https://butterfly.js.org/posts/4aa8abbe/#%E6%96%87%E7%AB%A0%E5%B0%81%E9%9D%A2
cover:
  # 是否顯示文章封面
  index_enable: true
  aside_enable: true
  archives_enable: true
  # 封面顯示的位置
  # 三個值可配置 left , right , both
  position: both
  # 當沒有設置cover時，默認的封面顯示
  default_cover:
    - https://cdn.jsdelivr.net/gh/jerryc127/CDN@latest/cover/default_bg.png
    - https://cdn.jsdelivr.net/gh/jerryc127/CDN@latest/cover/default_bg.png
    - https://cdn.jsdelivr.net/gh/jerryc127/CDN@latest/cover/default_bg.png

# 文章页相关配置
## https://butterfly.js.org/posts/4aa8abbe/#%E6%96%87%E7%AB%A0%E9%A0%81%E7%9B%B8%E9%97%9C%E9%85%8D%E7%BD%AE
post_meta:
  page:
    date_type: created # created or updated or both 主頁文章日期是創建日或者更新日或都顯示
    date_format: date # date/relative 顯示日期還是相對日期
    categories: true # true or false 主頁是否顯示分類
    tags: true # true or false 主頁是否顯示標籤
    label: true # true or false 顯示描述性文字
  post:
    date_type: both # created or updated or both 文章頁日期是創建日或者更新日或都顯示
    date_format: date # date/relative 顯示日期還是相對日期
    categories: true # true or false 文章頁是否顯示分類
    tags: true # true or false 文章頁是否顯示標籤
    label: true # true or false 顯示描述性文字

post_copyright:
  enable: true
  decode: false
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

reward:
  enable: true
  QR_code:
    - img: http://download.mariozzj.cn/img/picgo/20210920193422.jpg
      link:
      text: 微信
    - img: http://download.mariozzj.cn/img/picgo/20210920193431.jpg
      link:
      text: 支付宝

toc:
  enable: true
  number: true

related_post:
  enable: true
  limit: 3 # 顯示推薦文章數目
  date_type: created # or created or updated 文章日期顯示創建日或者更新日

anchor: true

post_pagination: 1

photofigcaption: true

# 头像
avatar:
  img: http://download.mariozzj.cn/img/picgo/20210920193818.jpg
  effect: false # 頭像會一直轉圈

# 复制配置
copy:
  enable: true
  copyright:
    enable: true
    limit_count: 50

# 页脚
footer:
  owner:
    enable: true
    since: 2020
  custom_text: Hi, this is MarioZZJ's Blog, welcome!
  copyright: true # Copyright of theme and framework
  ICP: # Chinese ICP License
    enable: true
    url: http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=42010602004261
    text: 鄂公网安备 42010602004261号
    icon: http://www.beian.gov.cn/img/new/gongan.png


# 功能按钮
## https://butterfly.js.org/posts/4aa8abbe/#%E5%8F%B3%E4%B8%8B%E8%A7%92%E6%8C%89%E9%88%95
darkmode:
  enable: true
  # dark mode和 light mode切換按鈕
  button: true
  autoChangeMode: 2

readmode: true

change_font_size: true

# 侧边栏
aside:
  enable: true
  hide: false
  button: true
  mobile: false # 手機頁面（ 顯示寬度 < 768px ）是否顯示aside內容
  position: right # left or right
  card_announcement:
    enable: true
    content: This is my Blog
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: true
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: YYYY-MM # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true

busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

runtimeshow:
  enable: true
  publish_date: 9/20/2021 00:00:00  